### PR TITLE
Some minor fixes.

### PR DESCRIPTION
**Pull request by Adib23704**
Fixes are done because of the latest Community Compiler enforces the usage of `const` as well as it triggers `error 017: undefined symbol "DEBUG_CODE_1"`

### CODE REVIEW

**Comment by NexiusTailer** [comment]
1. This doesn't fix const problem as with your changes it now wont compile on default samp compiler & includes.
2. You broke ru and by lang files by converting it to UTF-8, it's not supported in samp
3. `DEBUG_CODE`s should only be declared if the `#define DEBUG` is added

**Comment by NexiusTailer** [comment]
Ok, still 1 and 3 are valid

**Comment by Adib23704** [comment]
I mean when I was compiling it showed me undefined symbol DEBUG_CODE_1. I
had to comment out #if defined DEBUG condition to get out of this error.
(Same for other DEBUG_CODE vars)

For number 1, I don't know. Maybe you can check it out

**Comment by NexiusTailer** [comment]
> I mean when I was compiling it showed me undefined symbol DEBUG_CODE_1. I had to comment out #if defined DEBUG condition to get out of this error. (Same for other DEBUG_CODE vars)

So you probably manually included lang file without adding `#define DEBUG` as readme says

> For number 1, I don't know. Maybe you can check it out

Yes I've already checked it and it's not the solution. Solution is to be in line with default samp includes and don't change it with breaking changes like samp-stdlib does.

**Pull request closed without merging**
