### PR TITLE
Added georgian lang

### PR DESCRIPTION
**Pull request by Lashoo28**
i just added georgian lang

### CODE REVIEW

**Comment by NexiusTailer** [comment]
Thank you! But isn't this already added translation by you previously?
https://github.com/NexiusTailer/Nex-AC/tree/master/lang/nex-ac_ge.lang%20by%20lashona

If you wanna update your localization (if it's yours), you can update this existent file.

**Comment by Lashoo28** [comment]
It's not mine

**Comment by NexiusTailer** [comment]
Oh, sorry then. Ok, please create a folder with your nickname to put the .lang file inside it, just like it's done with others localizations.

**Comment by NexiusTailer** [comment]
Thank you again!

**Pull request merged**
