### PR TITLE
AT - Protection against attacks

### PR DESCRIPTION
**Pull request by Slayer360I**
AT - Protection against attacks (BOTS, falsification of information, etc.) Full support for all SAMP versions Algorithm error that reads only at BOTS/FAKE INFO

This will provide protection against attacks of this type for example and more of bypassing a ban by algorithm:
https://youtu.be/r6-VxKyvy3E
https://youtu.be/jCu_JjwR2oE

### CODE REVIEW

**Comment by NexiusTailer** [comment]
gpci is now properly faked by all more or less popular and updated sobeits automatically, not talking about it also can be easily bypassed with a bot. So, there is practically no point in this (just like the already existed protection by checking the player's client version to restrict connections from invalid versions or rakbots who have been sending it correctly for a long time, but this protection still remains for reasons of backward compatibility).

**Comment by NexiusTailer** [comment]
As for this statement:
> more (protection ) of bypassing a ban by algorithm

Just don't ban players by gpci as it's not reliable (as said above) nor unique identifier. Bans should affect account and/or player IP addresses only.

**Comment by Slayer360I** [comment]
Ok I get it, I disagree with you but ok.

Can you delete this please?

**Comment by 738765194** [comment]
Fly.all.luac, a plug-in plugin, sends a local package that can't be repaired. It's similar to driving a car without collision. The cleo car will fly.



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 9, 2022 08:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [NexiusTailer/Nex-AC] - (PR #280)




 
Ok I get it, I disagree with you but ok.
 
Can you delete this please?

**Comment by Slayer360I** [comment]
Because there are many cheaters who read this. And if you didn't add
So it's better not to show it

**Comment by NexiusTailer** [comment]
[But You already released it](https://github.com/Slayer360I/AT/blob/main/AT.pwn) (not even talking about [that](https://github.com/RogueDrifter/Anti_cheat_pack/blob/master/Anti-Cheat/FakeConnect.inc) which was released far earlier).

**Comment by Slayer360I** [comment]
Yes, but this area with you is called all the time... not with me, do you understand?
I would appreciate it if you could delete it

**Comment by NexiusTailer** [comment]
No, I didn’t understand what you are talking about and to be honest it looks completely ridiculous: like, you **publicly** offer unreliable protection, which has been easily bypassed for a long time, but at the same moment, when its merge fails, you are worried that someone will **see** it? 🤨 Where's the logic..

I can delete it if you asks ofc, but only because you just insist on it.

**Comment by RogueDrifter** [comment]
RogueDrifter confirms that gpci works in detecting raksamp. 😎

**Comment by RogueDrifter** [comment]
@Slayer360I Next time you copy my code give me credit YOU FUCK

**Comment by NexiusTailer** [comment]
> RogueDrifter confirms that gpci works in detecting raksamp. 😎 PS. Hi @NexiusTailer

I repeat personally to the RogueDrifter that this is easily bypassed even by a regular s0b, and therefore does not make practical sense.
PS. Hi @RogueDrifter

**Pull request closed without merging**
