### PR TITLE
Perfect invisible fix

### PR DESCRIPTION
**Pull request by Aleks4k**
This version addresses the cheat detection issue demonstrated in the video below:
https://www.youtube.com/watch?v=Qkq5tHZsCSk
Detection is working for past 3 years on Mexico DM without false toggles.

### CODE REVIEW

**Comment by NexiusTailer** [comment]
Thank you for the PR, but:
This cheat is called "afk ghost" or "ghost shooting" and there's already the code to detect this, it's 034 (anti-afk ghost). The reason why it doesn't detect the implementation from the video above is that it has to little distance by x/y/z, so it goes undetected. Anyway, I think it's better to improve code 034 instead of adding new code with similar checks, which in your case also doesn't consider surfing players (which may be surfing on moving objects or vehicles and the distance in such case should be more than 5.0 units) and it also doesn't consider players who shoot as vehicle passengers (the distance also must more more than 5.0 units for them to avoid false detections).

**Comment by Aleks4k** [comment]
Just finished testing the anti-cheat cases. As mentioned, this anti-cheat system has been in use for 3 years and operates without issues. 
During testing on the surfing object numbers never exceed 1.56, regardless of the surfing direction. 
For passengers, the numbers do not exceed 0.76. 
Additionally, I suggest adding the following line to the OnPlayerSpawn function to reset the cheat count:
`ACInfo[playerid][acCheatCount][22] = 0;`.

**Comment by NexiusTailer** [comment]
> Just finished testing the anti-cheat cases. As mentioned, this anti-cheat system has been in use for 3 years and operates without issues.

However I just listed all the potential problems:
1) It doesn't consider surfing players on objects which may shoot from weapon at that time and have more than 5 unis between their actual position and the shoot origin
2) It doesn't consider surfing players on vehicle which may shoot from weapon at that time and have more than 5 unis between their actual position and the shoot origin
3) It doesn't consider players in vehicle which may shoot from weapon at that time and have more than 5 unis between their actual position and the shoot origin

**Comment by Aleks4k** [comment]
Hi,

I've tested the implementation you provided, and it does not address the issue. The cheat you mentioned only modifies the Z coordinate, leaving the X and Y coordinates unchanged, which means the player's distance will not exceed 15.0. Additionally, I reviewed the server_log.txt for the past three months and found no instances of kicks related to this cheat, indicating that it is not being used anymore.

Additionally, I reviewed the server_log.txt for the past 3 months on my server and found no instances of kicks related to this cheat, indicating that it is no longer in use. Ping issues and packet loss could have led to false kicks during this period, as our server has an average of 30-40 players, and considering that the hosting is in France while part of our player base is from the Philippines, not everyone has perfect ping.

Anyways, since this cheat is no longer widely used, it may not be necessary to address it further.

**Comment by NexiusTailer** [comment]
> The cheat I mentioned only modifies the Z coordinate, leaving the X and Y coordinates unchanged, which means the player's distance will not exceed 15.0

This implementation also check specifically z difference and it checks for exactly the same 5.0 units, but only if player in not surfing and not in any vehicle. 15.0 units by Z axis will be applied if any of those statements are false (so if player surfs or seats in vehicle).

> Additionally, I reviewed the server_log.txt for the past three months and found no instances of kicks related to this cheat, indicating that it is not being used anymore.

I make tests on servers with 1000 players (such a sample is big enough and more or less representative) on projects such as Arizona RP, Evolve RP and some others. Unfortunately not everything can be catched in days/weeks even with such playerbase, so it makes me think through all the possible nuances in advance, even at the writing or code review stage.

If [this](https://github.com/NexiusTailer/Nex-AC/pull/326#issuecomment-2290952708) still detect a real cheat, I think it could be included in the next version with no problems.

**Comment by Aleks4k** [comment]
Somehow implementation which you provided does not work, I don't have time to find out why..

**Comment by NexiusTailer** [comment]
Ok, I just tested this on the local test server, seems working, thanks.

**Comment by NexiusTailer** [comment]
The proper fix is now in 1.9.65, thank you again for the cheat!

**Pull request closed without merging**
