### PR TITLE
🐛 fix(log): able to opt-out Nex-AC debug

### PR DESCRIPTION
**Pull request by rsetiawan7**
I've changed `#if defined DEBUG` to `#if defined NO_NEX_AC_DEBUG` to opt-out debug mode.

### CODE REVIEW

**Comment by NexiusTailer** [comment]
What problem is this intended to fix?

**Comment by rsetiawan7** [comment]
If you had `#define DEBUG`, it stills has output `[Nex-AC debug]` stuffs on server_log.txt

**Comment by NexiusTailer** [comment]
But if I merge you change, there will be problems "DEBUG" defined somewhere else, like in mysql.inc.

**Comment by rsetiawan7** [comment]
Maybe can we change `DEBUG` to `NEX_AC_DEBUG`? To make sure it's only used by Nex-AC.

**Comment by rsetiawan7** [comment]
I've changed `DEBUG` to `NEX_AC_DEBUG` to make it clear which part you want debug it.

 If you have any suggestions, please tell me.

**Comment by NexiusTailer** [comment]
> Maybe can we change DEBUG to NEX_AC_DEBUG? To make sure it's only used by Nex-AC.

This thing I should have done in the very first version, but now we have a lot of .lang files with "DEBUG" define checks and nothing can be done with it without breaking compatibility with current localization files. Even if you update every .lang file, they don't have versioning so people who use current files will face confusing problems and errors.

**Comment by rsetiawan7** [comment]
Do you have any suggestions to fix the debug thing?

**Comment by NexiusTailer** [comment]
At the moment, unfortunately, no. But I'm currently working on v2 version, where there will be a new project architecture, including new style of naming constants. So, all the current basic flaws that cannot be fixed due to backward compatibility can finally be resolved.

**Comment by rsetiawan7** [comment]
Okay... I'll close this pull request and add this issue as reminder.

Thanks for your suggestion!

**Pull request closed without merging**
